; PULPissimo Arty A7-100T PlatformIO example

[env:pulpissimo_arty_a7_100t]
platform = symlink://${sysenv.PULPISSIMO_ROOT}/platformio
board = pulpissimo_arty_a7_100t
framework = pulp-runtime
custom_pulpissimo_root = ${sysenv.PULPISSIMO_ROOT}
monitor_speed = 115200
upload_protocol = olimex-arm-usb-ocd-h
debug_tool = olimex-arm-usb-ocd-h
debug_init_break = tbreak main
